#!/usr/bin/env bash
# A script to install and configure HAProxy on lb-01 server
# This Configures HAProxy to send traffic to web-01 and web-02 servers
# This script Distributes requests using a roundrobin algorithm

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  fadafigo-frontend
        bind *:80
        mode http
        default_backend fadafigo-backend
backend fadafigo-backend
        balance roundrobin
        server 217345-web-01 100.26.214.96:80 check
        server 217345-web-02 34.207.189.108:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
